False: Non-zero return code, probably a syntax error occurred\ntime=1698713762.207246 gym-duckietown 2019.0.0

time=1698713762.3674762 Registering gym environment id: Duckietown-4way-v0
time=1698713762.367562 Registering gym environment id: Duckietown-ado_map_1-v0
time=1698713762.3675997 Registering gym environment id: Duckietown-ado_map_2-v0
time=1698713762.3676803 Registering gym environment id: Duckietown-loop_dyn_duckiebots-v0
time=1698713762.3677578 Registering gym environment id: Duckietown-loop_empty-v0
time=1698713762.3678412 Registering gym environment id: Duckietown-loop_obstacles-v0
time=1698713762.3679225 Registering gym environment id: Duckietown-loop_one_duckie-v0
time=1698713762.367974 Registering gym environment id: Duckietown-loop_only_duckies-v0
time=1698713762.3680298 Registering gym environment id: Duckietown-loop_pedestrians-v0
time=1698713762.3680787 Registering gym environment id: Duckietown-small_loop-v0
time=1698713762.368126 Registering gym environment id: Duckietown-small_loop_cw-v0
time=1698713762.3681788 Registering gym environment id: Duckietown-straight_road-v0
time=1698713762.3682387 Registering gym environment id: Duckietown-straight_road_10_tiles_no_start_tile-v0
time=1698713762.368292 Registering gym environment id: Duckietown-straight_road_no_start_tile-v0
time=1698713762.3683412 Registering gym environment id: Duckietown-straight_road_trafficlight-v0
time=1698713762.3683925 Registering gym environment id: Duckietown-straight_road_with_side_floor-v0
time=1698713762.368441 Registering gym environment id: Duckietown-udem1-v0
time=1698713762.368491 Registering gym environment id: Duckietown-zigzag_dists-v0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/ado_qualification/checker.py", line 2, in <module>
    from gym_duckietown.tasks.solution_evaluator import SameWeightSolutionEvaluator
  File "/home/appuser/aido-auto/gym-duckietown/gym_duckietown/tasks/solution_evaluator.py", line 101
    print(msg)
             ^
TabError: inconsistent use of tabs and spaces in indentation
